name: Minecraft-Sandbox
version: '${project.version}'
main: com.minecraft.sandbox.MinecraftSandbox
api-version: 1.18

commands:
  hello:
    description: "hello"
    usage: /hello
    permission: MinecraftSandbox.hello
