name: Minecraft-Sandbox
version: '1.0-SNAPSHOT'
main: com.minecraft.sandbox.MinecraftSandbox
api-version: 1.18

commands:
  hello:
    description: "hello"
    usage: /hello
    permission: MinecraftSandbox.hello
